### ISSUE TITLE
XHR 404 error when trying to create Monasca datasource

### ISSUE THREAD

**Issue by dhague** [rbak1/grafana-plugins#4]
Going to http://grafana.sap.corp:3000/datasources/new and selecting "Monasca", the following error pops up:

> Plugin Error
> Error: XHR error (404 Not Found) loading http://grafana.sap.corp:3000/public/app/plugins/datasource/grafana-monasca-datasource/module.js?bust=1466677850386 Error loading http://grafana.sap.corp:3000/public/app/plugins/datasource/grafana-monasca-datasource/module.js

**Comment by dhague** [comment]
Seems to be fixed by setting `"id": "monasca"` instead of `"id": "grafana-monasca-datasource"` in [datasources/monasca/plugin.json](https://github.com/twc-openstack/grafana-plugins/blob/master-monasca/datasources/monasca/plugin.json)

**Comment by rbak** [comment]
It seems like the id is supposed to match the name of the repo that the datasource is from.  I took a guess, although we'll need to change that to monasca-grafana-datasource once the permanent repo is set up.  I suspect this has to do with the way that the new grafana cli installs plugins, although I won't really know until we get the new repo setup.

Rather than changing the id, the fix for this issue is to put the datasource in in the directory with the id name.  If you take a look at your error you'll notice it's looking in plugins/datasource/grafana-monasca-datasource, whereas I'm guessing you were installing it in plugins/datasource/monasca
